### ISSUE TITLE
Can't make it work with shoe as the server-side

### ISSUE THREAD

**Issue by Floby** [Raynos/sockjs-stream#2]
I'm not sure this is supposed to be working but the following script doesn't work as I expect

``` javascript
var http = require('http');
var shoe = require('shoe');
var sockStream = require('sockjs-stream');

var server = http.createServer(function (req, res) {
  res.end('hello world\n');
});

var sock = shoe(function (stream) {
  console.log('got stream');
  stream.on('data', function(data) {
    console.log('echoing data', data);
    stream.write(data);
  });
});
sock.install(server, '/shoe');
server.listen(9000);

var stream = sockStream('ws://localhost:9000/shoe');
stream.write('Hello')
stream.end('world');

stream.on('connect', function() {
  console.log('connected !')
});
stream.on('data', function(data) {
  console.log('client data' , data)
});

```

hitting the server at `ws://localhost:9000/shoe/websocket` using `ws`  works (data events are being emitted). I can't make things work with sockjs-client.
It may be possible that this is a [data-channel](https://github.com/Raynos/data-channel) related bug.

My ultimate goal is to test a scuttlebutt model transmitting over a mux-demux-shoe stream from mocha. :D I was redirected to sockjs-stream from [here](https://github.com/substack/shoe/issues/24)

**Comment by Raynos** [comment]
just use shoe on the client instead.

Remind me to look into this after NKO.

**Comment by Floby** [comment]
Well, I haven't anything setup for integration testing for now. My server is mostly exposing JSON resources et scuttlebutt models. nothing too fancy.
FWIW, I managed to test it from node with this instead of sockjs-stream

``` js
var util = require('util');
var ws = require('ws');
var DuplexStream = require('stream').Duplex;

var Stream = module.exports = function Stream(uri) {
  if(!(this instanceof Stream)) return new Stream(uri);
  DuplexStream.apply(this);
  this.setEncoding('utf8');
  this._connected = false;
  this._writeQueue = [];

  var uri = uri + '/websocket';
  this._ws = new ws(uri);
  var self = this;
  this._ws.on('open', function() {
    self._connected = true;
    self.emit('open');
    self._flushQueue();
  });
  this._ws.on('message', function(message) {
    self.push(message.toString());
  });
};
util.inherits(Stream, DuplexStream);

Stream.prototype._write = function (chunk, encoding, callback) {
  if(!this._connected) {
    this._writeQueue.push(chunk.toString());
    return callback();
  }
  this._ws.send(chunk.toString());
  callback();
}

Stream.prototype._flushQueue = function () {
  var message;
  while(message = this._writeQueue.shift()) {
    this._ws.send(message);
  }
};

Stream.prototype._read = function () {
}
```

the mux-demux part has been copied locally from mux-demux-shoe/browser.js but uses this instread of shoe

**Comment by Raynos** [comment]
Oh you want to use sockjs within node. This might be a streams1 vs streams2 issue.

**Comment by dominictarr** [comment]
I can confirm this.
I seem to remember this working in the past...
I have a demo to reproduce here: 
https://github.com/dominictarr/bed/tree/master/example

(run server.js, and see that opening two browsers to localhost:3000 works, but node-client does not...)

**Comment by nrw** [comment]
@Floby and @dominictarr, will you check if you're still having this issue with `sockjs-stream` and `data-stream@0.2.0`? I think this is fixed. I also updated the `shoe` example in reconnect: https://github.com/dominictarr/reconnect/pull/23

**Comment by Raynos** [comment]
Created a new version sockjs-stream (1.0.0) that uses the latest data-channel.

**Comment by nrw** [comment]
I think the versions got jumbled. latest is `data-channel@0.2.1`. `sockjs-stream` was bumped to use `data-channel@0.1.2`.

**Comment by Raynos** [comment]
Fixed. v1.0.2
